# Generated by Django 5.2.2 on 2025-06-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL别名')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='特色图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐文章')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='允许评论')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='SEO标题')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=100, verbose_name='SEO关键词')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='作者姓名')),
                ('author_email', models.EmailField(max_length=254, verbose_name='作者邮箱')),
                ('author_url', models.URLField(blank=True, verbose_name='作者网站')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
    ]
