# Generated by Django 5.2.2 on 2025-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='位置名称'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
