# Generated by Django 5.2 on 2025-04-29 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_identifier', models.CharField(help_text='设备或App用于识别型号的唯一字符串，例如 SuperCooker-X1', max_length=100, unique=True, verbose_name='型号标识')),
                ('name', models.CharField(max_length=150, verbose_name='型号名称')),
                ('command_template', models.JSONField(blank=True, help_text='用于生成设备特定命令的JSON结构或模板', null=True, verbose_name='命令模板')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('ingredients', models.JSONField(blank=True, help_text="结构化配料列表，例如 [{'name': '五花肉', 'quantity': 500, 'unit': '克'}]", null=True, verbose_name='配料')),
                ('instructions', models.TextField(verbose_name='步骤')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='准备时间 (分钟)')),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='烹饪时间 (分钟)')),
                ('servings', models.PositiveIntegerField(blank=True, null=True, verbose_name='份量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('compatible_models', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.devicemodel', verbose_name='兼容型号')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
