# Generated by Django 5.2 on 2025-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝')], default='draft', max_length=10, verbose_name='状态'),
        ),
    ]
