# Generated by Django 5.2 on 2025-04-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_devicemodel_review_comment_devicemodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='collection_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='comal_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='烤盘位置'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='烹饪时间(小时)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '简单'), (2, '适中'), (3, '困难')], default=1, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='order',
            field=models.CharField(blank=True, max_length=200, verbose_name='指令码'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='page_view',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='准备时间(小时)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='staple_food',
            field=models.JSONField(blank=True, help_text="结构化主料列表，例如 [{'name': '猪瘦肉', 'value': 400, 'unit': 'g'}]", null=True, verbose_name='主料'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(blank=True, help_text="结构化步骤列表，例如 [{'stepNo': 1, 'stepDescription': '准备食材', 'imageUrl': 'http://example.com/img.jpg'}]", null=True, verbose_name='步骤'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='suitable_person',
            field=models.IntegerField(choices=[(1, '老人'), (2, '成人'), (3, '儿童'), (4, '婴幼儿')], default=2, verbose_name='适合人群'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔，如：早餐,猪肉,粥汤', max_length=200, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='temperature_unit',
            field=models.CharField(blank=True, default='℃', max_length=10, verbose_name='温度单位'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='temperature_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='温度值'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, verbose_name='小贴士'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='work_modes',
            field=models.CharField(blank=True, help_text='用逗号分隔，如：微波,烧烤', max_length=200, verbose_name='工作模式'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='烹饪时间(分钟)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, help_text="结构化辅料列表，例如 [{'name': '姜', 'value': 3, 'unit': '片'}]", null=True, verbose_name='辅料'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='准备时间(分钟)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='菜谱名称'),
        ),
    ]
