# Generated by Django 5.2 on 2025-04-30 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_remove_recipe_instructions_recipe_collection_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.devicemodel', verbose_name='设备型号')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_content', models.TextField(help_text='JSON格式的命令内容', verbose_name='命令内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.device', verbose_name='设备')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱设备关联',
                'verbose_name_plural': '菜谱设备关联',
                'unique_together': {('recipe', 'device')},
            },
        ),
        migrations.CreateModel(
            name='RecipeDeviceCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_template', models.TextField(help_text='JSON格式的命令模板', verbose_name='命令模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.devicemodel', verbose_name='设备型号')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱设备兼容性',
                'verbose_name_plural': '菜谱设备兼容性',
                'unique_together': {('recipe', 'device_model')},
            },
        ),
    ]
